name: flutter_basics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.2.1
  json_annotation: ^4.8.1
  meta: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
